title: Numrich Albrecht Klumpp
email: jhh@j2h.com
description: Numrich Albrecht Klumpp Gesellschaft von Architekten mbH
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://nak-architekten.j2h.com/" # the base hostname & protocol for your site
markdown: kramdown
cloudinaryaccount: "dpcao7gpf"